---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-fhivemind-io-v1-plant
  failurePolicy: Fail
  name: mplant.kb.io
  rules:
  - apiGroups:
    - operator.fhivemind.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - plants
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-fhivemind-io-v1-plant
  failurePolicy: Fail
  name: vplant.kb.io
  rules:
  - apiGroups:
    - operator.fhivemind.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - plants
  sideEffects: None
