# permissions for end users to edit plants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: plant-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: plant-operator
    app.kubernetes.io/part-of: plant-operator
    app.kubernetes.io/managed-by: kustomize
  name: plant-editor-role
rules:
- apiGroups:
  - operator.cisco.io
  resources:
  - plants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.cisco.io
  resources:
  - plants/status
  verbs:
  - get
